# Configuration for eureka naming server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defautlZone: htpp://localhost:8761/eureka/
  instance:
    hostname: localhost
